### ISSUE TITLE
Data validation using database connection

### ISSUE THREAD

**Issue by Sam-R** [chris-schmitz/L5SimpleFM#2]
So, I've got everything setup and it's working great with the .env file settings, but I was wondering if it's possible to set L5SimpleFM as the default database connection?

Specifically, what I'm trying to do is to call validation rules on the database using Laravel's Validator class. Eg:

``` php
$validator = Validator::make($request->getContent(), [
'company_ref' => 'required|alpha_num|unique:mdl_Companies,company_ref',
]);
```

But, after following the setup notes, I've found that the validator uses the default connection specified in `database.confg` which I'm not sure how to configure to be L5SimpleFM?

**Comment by chris-schmitz** [comment]
Hey Sam,

At the moment L5SimpleFM doesn't use Laravel's Eloquent structure, it's a separate database access method. 

I couldn't build it into Eloquent itself because behind the scenes Eloquent is using sql statements to query the data and FileMaker's custom web publishing doesn't work with sql. 

It may be possible to make FileMaker accessible via Eloquent by implementing the interfaces Eloquent requires within L5SimpleFM, but it's not something I currently have time to explore.

For now I would suggest using the validator statement above minus the rule that requires database interaction: 

```
$validator = Validator::make($request->getContent(), [
    'company_ref' => 'required|alpha_num',
]);
```

And then within the FileMaker Model class you're using (here I'm assuming it's Company) create a method for the uniqueness check:

```
namespace MyApp\FileMakerModels; // whatever namespace you keep your FileMaker Model classes in

use App\FileMakerModels\BaseModel;

class Company extends BaseModel
{
    protected $layoutName = 'mdl_Companies';

    public function findCompanyByRef($ref){
        try {
            $result = $this->findByFields(['company_ref', $ref])->executeCommand();
        } catch (\RecordsNotFoundException $e) {
            return false;           
        }
        return $result->getRows();
    }
}
```

Then you could use this method to determine if the company is unique:

```
if ( $this->company->findCompanyByRef($request->input('company_ref')) !== false ){ // if it's not false, meaning we found a company with this ref
    // error out because we found at least one match
}
```

Sorry I don't have a better solution for you.
